import type { ReportResult } from "@/lib/reports/types";
import type { ShopReportData } from "@/lib/reports/shop-report-data";
import { buildReportInsights } from "@/lib/reports/report-insights";
import { getReportById } from "@/lib/reports/registry";
import { runShopReport } from "@/lib/reports/report-utils";
import {
  createCustomReportId,
  runCustomReport,
  type ReportDataSourceId,
  type SavedCustomReport,
} from "@/lib/reports/custom-report-builder";

export type AiChatMessage = {
  id: string;
  role: "user" | "assistant";
  content: string;
  reportResult?: ReportResult;
  reportId?: string;
  suggestions?: string[];
  /** When the assistant builds a new custom report config */
  customReportDraft?: SavedCustomReport;
};

type AiIntent = {
  reply: string;
  reportId?: string;
  customReport?: SavedCustomReport;
  suggestions?: string[];
};

const STARTER_SUGGESTIONS = [
  "Give me a shop overview",
  "Show machine productivity",
  "Who are my top customers?",
  "Export rush orders",
  "Show employee productivity",
  "Which items are low on stock?",
];

function buildDraftCustomReport(
  partial: Pick<SavedCustomReport, "title" | "description" | "sourceId" | "columns" | "filters">
): SavedCustomReport {
  const now = new Date().toISOString();
  return {
    id: createCustomReportId(),
    ...partial,
    createdAt: now,
    updatedAt: now,
  };
}

/** Try to build a custom report from natural language */
function parseCustomReportRequest(message: string): SavedCustomReport | null {
  const text = message.toLowerCase();

  if (text.includes("rush") && (text.includes("order") || text.includes("report"))) {
    return buildDraftCustomReport({
      title: "Rush orders",
      description: "Generated by insights assistant",
      sourceId: "orders",
      columns: [
        "orderNumber",
        "customer",
        "status",
        "inHandsDate",
        "rush",
        "total",
        "balance",
      ],
      filters: [{ field: "rush", operator: "equals", value: "Yes" }],
    });
  }

  if (
    (text.includes("custom") || text.includes("build") || text.includes("create")) &&
    (text.includes("line item") || text.includes("blank") || text.includes("garment"))
  ) {
    return buildDraftCustomReport({
      title: "Line items",
      description: "Generated by insights assistant",
      sourceId: "line_items",
      columns: [
        "orderNumber",
        "customer",
        "product",
        "brand",
        "color",
        "quantity",
      ],
      filters: [],
    });
  }

  if (text.includes("open task") || text.includes("pending task")) {
    return buildDraftCustomReport({
      title: "Open tasks",
      description: "Generated by insights assistant",
      sourceId: "tasks",
      columns: ["title", "assignee", "status", "dueDate", "orderNumber", "customer"],
      filters: [{ field: "status", operator: "equals", value: "pending" }],
    });
  }

  if (text.includes("shipment") || text.includes("pickup") || text.includes("tracking")) {
    return buildDraftCustomReport({
      title: "Shipments",
      description: "Generated by insights assistant",
      sourceId: "shipments",
      columns: [
        "orderNumber",
        "customer",
        "method",
        "status",
        "destination",
        "tracking",
      ],
      filters: [],
    });
  }

  return null;
}

function matchIntent(message: string, data: ShopReportData): AiIntent {
  const text = message.toLowerCase().trim();
  const insights = buildReportInsights(data);

  const customDraft = parseCustomReportRequest(message);
  if (customDraft) {
    return {
      reply: `I built a custom report "${customDraft.title}" from your request. Preview the rows below, export to CSV, or save it to your library.`,
      customReport: customDraft,
      suggestions: ["Save to my library", "Show machine productivity"],
    };
  }

  if (/^(hi|hello|hey)\b/.test(text)) {
    return {
      reply:
        "Hi! I can analyze your shop data and generate exportable reports. Ask about revenue, production, team performance, inventory, or say \"give me a shop overview\".",
      suggestions: STARTER_SUGGESTIONS.slice(0, 4),
    };
  }

  if (text.includes("help") || text.includes("what can you")) {
    return {
      reply:
        "I can explore your shop data and generate reports. Try:\n\n• Machine or employee productivity\n• Revenue and top customers\n• Rush or past-due orders\n• Inventory and purchase orders\n• Custom reports — e.g. \"build a report of rush orders\"",
      suggestions: STARTER_SUGGESTIONS,
    };
  }

  if (
    text.includes("machine") &&
    (text.includes("product") || text.includes("utiliz") || text.includes("busy"))
  ) {
    return {
      reply:
        "Here's your machine productivity breakdown — scheduled hours, completed runs, and pieces per machine.",
      reportId: "machine-productivity",
      suggestions: ["Show production schedule", "Show floor job runs"],
    };
  }

  if (
    text.includes("employee") ||
    text.includes("team") ||
    text.includes("staff") ||
    (text.includes("who") && text.includes("working"))
  ) {
    return {
      reply:
        "This report shows assignments, completed events, floor notes, and open tasks per team member.",
      reportId: "employee-productivity",
      suggestions: ["Show team roster", "Show shop tasks"],
    };
  }

  if (text.includes("task") && !text.includes("machine")) {
    return {
      reply: "All shop tasks with assignee, department, status, and due dates.",
      reportId: "shop-tasks",
      suggestions: ["Show employee productivity", "Open tasks report"],
    };
  }

  if (
    text.includes("revenue") ||
    text.includes("sales") ||
    text.includes("money") ||
    text.includes("top customer")
  ) {
    if (text.includes("customer") || text.includes("top")) {
      return {
        reply:
          "Here are your customers ranked by revenue, open balance, and order activity.",
        reportId: "sales-by-customer",
        suggestions: ["Show revenue by order", "Show pipeline summary"],
      };
    }
    return {
      reply:
        "Here's revenue broken down by order with totals, payments, and balances.",
      reportId: "revenue-by-order",
      suggestions: ["Sales by decoration", "Pipeline summary"],
    };
  }

  if (text.includes("rush")) {
    return {
      reply: "All rush-flagged orders with status, in-hands dates, and balances.",
      reportId: "rush-orders",
      suggestions: ["Past due orders", "Show pipeline"],
    };
  }

  if (
    text.includes("past due") ||
    text.includes("overdue") ||
    text.includes("late")
  ) {
    return {
      reply: "Active orders that are past their in-hands date.",
      reportId: "past-due-orders",
      suggestions: ["Customers with open balances", "Rush orders"],
    };
  }

  if (
    text.includes("balance") ||
    text.includes("owe") ||
    text.includes("outstanding") ||
    text.includes("billing")
  ) {
    const balanceInsight = insights.find((item) => item.id === "open-balance");
    return {
      reply: balanceInsight
        ? `Your shop has ${balanceInsight.value} in open balances across active orders. Here's the detailed billing report.`
        : "Here's your customers with open balances report.",
      reportId: "customers-open-balances",
      suggestions: ["Revenue by order", "Past due orders"],
    };
  }

  if (
    text.includes("inventory") ||
    text.includes("stock") ||
    text.includes("sku")
  ) {
    if (text.includes("low")) {
      return {
        reply: "These SKUs are at or below their reorder point.",
        reportId: "low-stock",
        suggestions: ["Full inventory status", "Purchase orders"],
      };
    }
    return {
      reply: "Full inventory status with on-hand quantities and reorder points.",
      reportId: "inventory-status",
      suggestions: ["Low stock items", "Purchase orders"],
    };
  }

  if (text.includes("purchase") || text.includes("po ")) {
    return {
      reply: "Purchase orders with vendor, status, and line item totals.",
      reportId: "purchase-orders",
      suggestions: ["Inventory status", "Low stock"],
    };
  }

  if (
    text.includes("schedule") ||
    text.includes("calendar") ||
    text.includes("production schedule")
  ) {
    return {
      reply:
        "Your full production schedule with machines, orders, and run status.",
      reportId: "schedule-detail",
      suggestions: ["Machine productivity", "Floor job runs"],
    };
  }

  if (
    text.includes("floor") ||
    text.includes("job run") ||
    text.includes("running")
  ) {
    return {
      reply: "Floor job runs with start/finish times and duration per block.",
      reportId: "floor-job-runs",
      suggestions: ["Production schedule", "All production events"],
    };
  }

  if (
    text.includes("shipment") ||
    text.includes("ship") ||
    text.includes("pickup") ||
    text.includes("tracking")
  ) {
    return {
      reply: "Shipments and pickups with destination, method, and tracking.",
      reportId: "shipments",
      suggestions: ["All customer orders", "Revenue by order"],
    };
  }

  if (
    text.includes("decoration") ||
    text.includes("screen print") ||
    text.includes("embroidery") ||
    text.includes("dtf")
  ) {
    return {
      reply: "Revenue and event counts grouped by decoration type.",
      reportId: "sales-by-decoration",
      suggestions: ["All production events", "Line item detail"],
    };
  }

  if (text.includes("pipeline")) {
    return {
      reply: "Open orders grouped by status with pipeline value.",
      reportId: "pipeline-summary",
      suggestions: ["Revenue by order", "Rush orders"],
    };
  }

  if (text.includes("customer") && text.includes("export")) {
    return {
      reply:
        "Complete customer export with orders, line items, and production data.",
      reportId: "complete-customer-export",
      suggestions: ["Customer directory", "Customer profiles"],
    };
  }

  if (
    text.includes("line item") ||
    text.includes("blank") ||
    text.includes("garment")
  ) {
    return {
      reply: "Line items with products, brands, colors, and quantities.",
      customReport: buildDraftCustomReport({
        title: "Line items",
        description: "Generated by insights assistant",
        sourceId: "line_items",
        columns: [
          "orderNumber",
          "customer",
          "product",
          "brand",
          "color",
          "quantity",
        ],
        filters: [],
      }),
      suggestions: ["Most common blanks", "Sales by decoration"],
    };
  }

  if (
    text.includes("issue") &&
    (text.includes("machine") || text.includes("floor"))
  ) {
    return {
      reply: "Machine issue reports from the floor.",
      reportId: "machine-issues",
      suggestions: ["Machine productivity", "Production schedule"],
    };
  }

  if (
    text.includes("insight") ||
    text.includes("summary") ||
    text.includes("overview")
  ) {
    const top = insights.slice(0, 5);
    const summary = top
      .map((item) => `• ${item.title}: ${item.value} — ${item.detail}`)
      .join("\n");
    return {
      reply: `Here's a snapshot of your shop right now:\n\n${summary}\n\nTap any suggestion below to drill in, or ask me to build a custom report.`,
      suggestions: STARTER_SUGGESTIONS.slice(0, 4),
    };
  }

  return {
    reply:
      "I can help with machine productivity, employee performance, revenue, customers, inventory, scheduling, and custom reports. Try being specific — for example, \"show machine productivity\" or \"build a report of rush orders\".",
    suggestions: STARTER_SUGGESTIONS,
  };
}

export function getAiStarterSuggestions(): string[] {
  return STARTER_SUGGESTIONS;
}

export function hydrateChatMessages(
  messages: AiChatMessage[],
  data: ShopReportData
): AiChatMessage[] {
  return messages.map((message) => {
    if (message.reportResult) return message;

    if (message.reportId) {
      const report = getReportById(message.reportId);
      if (report) {
        return { ...message, reportResult: runShopReport(report, data) };
      }
    }

    if (message.customReportDraft) {
      return {
        ...message,
        reportResult: runCustomReport(message.customReportDraft, data),
      };
    }

    return message;
  });
}

export function buildAssistantMessageFromApi(
  response: {
    reply: string;
    reportId?: string | null;
    customReport?: SavedCustomReport | null;
    suggestions?: string[];
  },
  data: ShopReportData
): AiChatMessage {
  let reportResult: ReportResult | undefined;
  let reportId = response.reportId || undefined;
  let customReportDraft = response.customReport || undefined;

  if (response.reportId) {
    const report = getReportById(response.reportId);
    if (report) {
      reportResult = runShopReport(report, data);
    }
  } else if (response.customReport) {
    reportResult = runCustomReport(response.customReport, data);
    reportId = response.customReport.id;
  }

  return {
    id: `assistant-${Date.now()}`,
    role: "assistant",
    content: response.reply,
    reportResult,
    reportId,
    customReportDraft,
    suggestions: response.suggestions,
  };
}

export function processAiMessage(
  message: string,
  data: ShopReportData
): AiChatMessage {
  const intent = matchIntent(message, data);
  let reportResult: ReportResult | undefined;
  let reportId = intent.reportId;
  let customReportDraft = intent.customReport;

  if (intent.reportId) {
    const report = getReportById(intent.reportId);
    if (report) {
      reportResult = runShopReport(report, data);
    }
  } else if (intent.customReport) {
    reportResult = runCustomReport(intent.customReport, data);
    reportId = intent.customReport.id;
  }

  return {
    id: `assistant-${Date.now()}`,
    role: "assistant",
    content: intent.reply,
    reportResult,
    reportId,
    customReportDraft,
    suggestions: intent.suggestions,
  };
}

export function createUserMessage(content: string): AiChatMessage {
  return {
    id: `user-${Date.now()}`,
    role: "user",
    content,
  };
}

export function isSaveToLibraryRequest(message: string): boolean {
  const text = message.toLowerCase();
  return (
    text.includes("save") &&
    (text.includes("library") || text.includes("custom") || text.includes("report"))
  );
}

export type ReportDataSourceSummary = {
  id: ReportDataSourceId | "customers";
  label: string;
  count: number;
};

export function summarizeDataSources(data: ShopReportData): ReportDataSourceSummary[] {
  return [
    { id: "orders", label: "Orders", count: data.orders.length },
    { id: "customers", label: "Customers", count: data.customers.length },
    { id: "schedule_blocks", label: "Schedule blocks", count: data.scheduleBlocks.length },
    { id: "job_runs", label: "Job runs", count: data.jobRuns.length },
    { id: "machines", label: "Machines", count: data.machines.length },
    { id: "team_members", label: "Team", count: data.teamMembers.length },
    { id: "inventory", label: "Inventory SKUs", count: data.inventory.length },
    {
      id: "purchase_orders",
      label: "Purchase orders",
      count: data.purchaseOrders.length,
    },
  ];
}
